name: Add Assignee
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  add_assignee:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            assignees:[context.repo.owner]
            });
